### ISSUE TITLE
How to add new products  

### ISSUE THREAD

**Issue by roshni2154** [ashraf-kabir/mern-ecommerce#49]
hey how can i add new products and render them. 
  /create/product

not working..

**Comment by ashraf-kabir** [comment]
it supposed to work. attach screenshot

**Comment by ashraf-kabir** [comment]
you need to setup your database either locally or at mongodb.

**Comment by ashraf-kabir** [comment]
![image](https://user-images.githubusercontent.com/30576323/231807921-391320ae-8f07-4ec3-8fa6-69fbdb569cae.png)
It works. You have some errors at your end. Check console.
