### ISSUE TITLE
I did everything still it's not able to run the application even though my MongoDB is working completely fine. The website is running but the database isn't reacting(after signing up nothing happens it remains in the same state as a static website) Please help me with this if you want I could send you my whole code my end-sem project submission is really close🙏🙏

### ISSUE THREAD

**Issue by Yashpakar** [ashraf-kabir/mern-ecommerce#52]
![image](https://user-images.githubusercontent.com/111524758/235352499-8ba15c6b-f1d0-4889-9bc7-72340b0c04b9.png)
this is the error that I'm getting

**Comment by prathamjagga** [comment]
in server.js change MONGOURI to MONGODB_URI it will be resolved

**Comment by ashraf-kabir** [comment]
https://github.com/ashraf-kabir/mern-ecommerce/commit/845d4c07bbf3b931d0e56e4a46ede663e50f678d

fixed
