### ISSUE TITLE
Admin role is not accessible

### ISSUE THREAD

**Issue by Amit00519** [ashraf-kabir/mern-ecommerce#54]
Admin role is not accessible

**Comment by cricgok** [comment]
Admin is not Accessible

**Comment by nithin3q** [comment]
firstly signup as user and change user role to any number except 0 in db manually

**Comment by nithin3q** [comment]
> firstly signup as user and change user role to any number except 0 in db manually



> Admin is not Accessible



> Admin is not Accessible

firstly signup as user and change user role to any number except 0 in db manually
